import { writeFileSync, readFileSync, existsSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

export async function initStandards(
  outputPath: string,
  interactive: boolean = true
): Promise<void> {
  let projectName = "My Website";
  let domain = "example.com";
  let framework = "Unknown";
  let language = "en";

  if (interactive) {
    const inquirer = await import("inquirer");
    const answers = await inquirer.default.prompt([
      {
        type: "input",
        name: "projectName",
        message: "Project/website name:",
        default: projectName,
      },
      {
        type: "input",
        name: "domain",
        message: "Production domain (e.g., example.com):",
        default: domain,
      },
      {
        type: "list",
        name: "framework",
        message: "Frontend framework:",
        choices: [
          "Next.js",
          "Nuxt",
          "Astro",
          "SvelteKit",
          "Remix",
          "Vite/React",
          "Vite/Vue",
          "Plain HTML",
          "Other",
        ],
        default: "Next.js",
      },
      {
        type: "input",
        name: "language",
        message: "Primary language code (e.g., en, es, fr):",
        default: language,
      },
    ]);
    projectName = answers.projectName;
    domain = answers.domain;
    framework = answers.framework;
    language = answers.language;
  }

  // Load the template
  const templatePath = resolve(__dirname, "../templates/web-standards.md");
  let template: string;

  if (existsSync(templatePath)) {
    template = readFileSync(templatePath, "utf-8");
  } else {
    template = getBuiltInTemplate();
  }

  // Replace placeholders
  const content = template
    .replaceAll("{{PROJECT_NAME}}", projectName)
    .replaceAll("{{DOMAIN}}", domain)
    .replaceAll("{{FRAMEWORK}}", framework)
    .replaceAll("{{LANGUAGE}}", language)
    .replaceAll("{{DATE}}", new Date().toISOString().split("T")[0]);

  writeFileSync(outputPath, content, "utf-8");
}

function getBuiltInTemplate(): string {
  // Fallback if template file not found — full standards embedded
  return `# Web Standards — {{PROJECT_NAME}}

> Generated by WebProbe on {{DATE}}
> Domain: {{DOMAIN}} | Framework: {{FRAMEWORK}} | Language: {{LANGUAGE}}

---

## Table of Contents
1. [SEO Standards](#seo-standards)
2. [Responsive Design](#responsive-design)
3. [Accessibility (A11y)](#accessibility)
4. [Performance](#performance)
5. [Visual Standards](#visual-standards)
6. [Code Quality](#code-quality)
7. [Security](#security)
8. [Meta & Social](#meta--social)

---

${FULL_STANDARDS_CONTENT}
`;
}

// This gets replaced by the actual template file — see templates/web-standards.md
const FULL_STANDARDS_CONTENT = "See templates/web-standards.md for complete standards.";
